# Copyright (c) 2025 HUSTJunshuang
# 
# Licensed under the MIT License. See LICENSE file in the project root for full license information.

import os
from kconfiglib import Kconfig

def dumpconf():
    # load '.config' generated by kconfig-mconf
    kconf = Kconfig()
    kconf.load_config(".config")
    # mkdir
    os.makedirs("include/generated", exist_ok = True)
    # generate autoconf.h
    kconf.write_autoconf()
    # generate auto.conf
    kconf.sync_deps("include/config")

if __name__ == "__main__":
    dumpconf()
